#!/bin/sh

#/var/opt/gitlab/git-data/repositories/service/xxx.git

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the PHP Lint Error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer Check. Code standard PSR2."
    D:/myFiles/PHP_CodeSniffer/bin/phpcs --standard=PSR2 --colors --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Code Sniffer Check Error!"

	echo "Running Code Sniffer Fix. Code standard:PSR2."
	D:/myFiles/PHP_CodeSniffer/bin/phpcbf --standard=PSR2 $FILES

	echo "Please recommit!"

        exit 1
    fi
fi

exit $?